/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../app/shared/stub.component/stub.component';
const styles_StubComponent:any[] = ([] as any[]);
export const RenderType_StubComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_StubComponent,
  data: {}
}
);
export function View_StubComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵqud(201326592,1,{stubBody: 0}),
    (l()(),import0.ɵted((null as any),[' '])),
    (l()(),import0.ɵeld(0,[
      [
        1,
        0
      ]
      ,
      [
        'stubBody',
        1
      ]

    ]
    ,(null as any),0,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)))
  ]
  ,(null as any),(null as any));
}
function View_StubComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'stub-cmpnt',([] as any[]),(null as any),(null as any),(null as any),View_StubComponent_0,RenderType_StubComponent)),
    import0.ɵdid(2121728,(null as any),0,import1.StubComponent,[import0.Renderer2],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const StubComponentNgFactory:import0.ComponentFactory<import1.StubComponent> = import0.ɵccf('stub-cmpnt',import1.StubComponent,View_StubComponent_Host_0,{body: 'stub-cmpnt-body'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvaW50ZXJuZXQvRG9jdW1lbnRzL0dpdEh1Yi9hbmd1bGFyMi9nZW5fZHJpZnQtbmdyeC00LXJjMy9hcHAvc2hhcmVkL3N0dWIuY29tcG9uZW50L3N0dWIuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL2ludGVybmV0L0RvY3VtZW50cy9HaXRIdWIvYW5ndWxhcjIvZ2VuX2RyaWZ0LW5ncngtNC1yYzMvYXBwL3NoYXJlZC9zdHViLmNvbXBvbmVudC9zdHViLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL2ludGVybmV0L0RvY3VtZW50cy9HaXRIdWIvYW5ndWxhcjIvZ2VuX2RyaWZ0LW5ncngtNC1yYzMvYXBwL3NoYXJlZC9zdHViLmNvbXBvbmVudC9zdHViLmNvbXBvbmVudC50cy5TdHViQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9DOi9Vc2Vycy9pbnRlcm5ldC9Eb2N1bWVudHMvR2l0SHViL2FuZ3VsYXIyL2dlbl9kcmlmdC1uZ3J4LTQtcmMzL2FwcC9zaGFyZWQvc3R1Yi5jb21wb25lbnQvc3R1Yi5jb21wb25lbnQudHMuU3R1YkNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIiA8ZGl2ICNzdHViQm9keT48L2Rpdj4iLCI8c3R1Yi1jbXBudD48L3N0dWItY21wbnQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUFDO01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O0lBQUE7S0FBQTs7Ozs7O0lDQUQ7Z0JBQUE7Ozs7In0=
