/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../app/app.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/router';
import * as import4 from '@angular/platform-browser';
import * as import5 from '@angular/forms';
import * as import6 from '@angular/material';
import * as import7 from '@angular/http';
import * as import8 from '../../app/shared/shared.module';
import * as import9 from '../../app/core/app-routing.module';
import * as import10 from '../../app/core/core.module';
import * as import11 from '@angular/platform-browser/animations';
import * as import12 from '@ngrx/store/src/ng2';
import * as import13 from '@ngrx/router-store/src/router-store-module';
import * as import14 from '@ngrx/store-devtools/src/instrument';
import * as import15 from '../../app/app.configs/hammerjs.config';
import * as import16 from '@ngrx/store/src/dispatcher';
import * as import17 from '../../app/services/d3.service';
import * as import18 from '../../app/services/dialogs.service';
import * as import19 from '@ngrx/store-devtools/src/extension';
import * as import20 from '@ngrx/store-devtools/src/devtools';
import * as import21 from '../../app/services/error.handler.service';
import * as import22 from '../node_modules/@angular/material/typings/index.ngfactory';
import * as import23 from './core/inctruction.component/instruction.component.ngfactory';
import * as import24 from './core/modeling.component/modeling.component.ngfactory';
import * as import25 from './core/page.404.component/page.404.component.ngfactory';
import * as import26 from './shared/modal_window.component/modal_window.component.ngfactory';
import * as import27 from './AppComponent.ngfactory';
import * as import28 from '../../app/core/inctruction.component/instruction.component';
import * as import29 from '../../app/core/modeling.component/modeling.component';
import * as import30 from '../../app/core/page.404.component/page.404.component';
import * as import31 from '../../app/store.reducers/index';
import * as import32 from '@angular/animations/browser';
import * as import33 from '@ngrx/store/src/reducer';
import * as import34 from '@ngrx/store/src/state';
import * as import35 from '@ngrx/store/src/store';
import * as import36 from '@ngrx/store-devtools/src/config';
class AppModuleInjector extends import0.ɵNgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ErrorHandler_1:any;
  _NgProbeToken_2:any[];
  _ɵg_3:import3.ɵg;
  _APP_INITIALIZER_4:any[];
  _ApplicationInitStatus_5:import0.ApplicationInitStatus;
  _ɵf_6:import0.ɵf;
  _ApplicationRef_7:any;
  _ApplicationModule_8:import0.ApplicationModule;
  _BrowserModule_9:import4.BrowserModule;
  _ɵba_10:import5.ɵba;
  _FormsModule_11:import5.FormsModule;
  _PortalModule_12:import6.PortalModule;
  _OverlayModule_13:import6.OverlayModule;
  _PlatformModule_14:import6.PlatformModule;
  _A11yModule_15:import6.A11yModule;
  _CompatibilityModule_16:import6.CompatibilityModule;
  _MdDialogModule_17:import6.MdDialogModule;
  _MdRippleModule_18:import6.MdRippleModule;
  _MdSelectionModule_19:import6.MdSelectionModule;
  _MdOptionModule_20:import6.MdOptionModule;
  _MdAutocompleteModule_21:import6.MdAutocompleteModule;
  _StyleModule_22:import6.StyleModule;
  _MdButtonModule_23:import6.MdButtonModule;
  _MdButtonToggleModule_24:import6.MdButtonToggleModule;
  _MdCardModule_25:import6.MdCardModule;
  _MdChipsModule_26:import6.MdChipsModule;
  _MdCheckboxModule_27:import6.MdCheckboxModule;
  _MdLineModule_28:import6.MdLineModule;
  _MdGridListModule_29:import6.MdGridListModule;
  _HttpModule_30:import7.HttpModule;
  _MdIconModule_31:import6.MdIconModule;
  _MdInputModule_32:import6.MdInputModule;
  _MdListModule_33:import6.MdListModule;
  _MdMenuModule_34:import6.MdMenuModule;
  _MdProgressBarModule_35:import6.MdProgressBarModule;
  _MdProgressSpinnerModule_36:import6.MdProgressSpinnerModule;
  _MdRadioModule_37:import6.MdRadioModule;
  _MdSelectModule_38:import6.MdSelectModule;
  _MdSidenavModule_39:import6.MdSidenavModule;
  _RtlModule_40:import6.RtlModule;
  _MdSliderModule_41:import6.MdSliderModule;
  _MdSlideToggleModule_42:import6.MdSlideToggleModule;
  _MdSnackBarModule_43:import6.MdSnackBarModule;
  _ObserveContentModule_44:import6.ObserveContentModule;
  _MdTabsModule_45:import6.MdTabsModule;
  _MdToolbarModule_46:import6.MdToolbarModule;
  _MdTooltipModule_47:import6.MdTooltipModule;
  _MaterialModule_48:import6.MaterialModule;
  _SharedModule_49:import8.SharedModule;
  _ɵa_50:any;
  _UrlSerializer_51:import3.DefaultUrlSerializer;
  _RouterOutletMap_52:import3.RouterOutletMap;
  _ROUTER_CONFIGURATION_53:any;
  _LocationStrategy_54:any;
  _Location_55:import2.Location;
  _Compiler_56:import0.Compiler;
  _NgModuleFactoryLoader_57:import0.SystemJsNgModuleLoader;
  _ROUTES_58:any[];
  _Router_59:any;
  _RouterModule_60:import3.RouterModule;
  _AppRoutingModule_61:import9.AppRoutingModule;
  _CoreModule_62:import10.CoreModule;
  _BrowserAnimationsModule_63:import11.BrowserAnimationsModule;
  _StoreModule_64:import12.StoreModule;
  _RouterStoreModule_65:import13.RouterStoreModule;
  _StoreDevtoolsModule_66:import14.StoreDevtoolsModule;
  _AppModule_67:import1.AppModule;
  __LOCALE_ID_68:any;
  __NgLocalization_69:import2.NgLocaleLocalization;
  __APP_ID_70:any;
  __IterableDiffers_71:any;
  __KeyValueDiffers_72:any;
  __DomSanitizer_73:import4.ɵe;
  __Sanitizer_74:any;
  __HAMMER_GESTURE_CONFIG_75:import15.HammerConfig;
  __EVENT_MANAGER_PLUGINS_76:any[];
  __EventManager_77:import4.EventManager;
  __ɵDomSharedStylesHost_78:import4.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_79:import4.ɵDomRendererFactory2;
  __AnimationDriver_80:any;
  __ɵAnimationStyleNormalizer_81:any;
  __ɵAnimationEngine_82:import11.ɵa;
  __RendererFactory2_83:any;
  __ɵSharedStylesHost_84:any;
  __Testability_85:import0.Testability;
  __Meta_86:import4.Meta;
  __Title_87:import4.Title;
  __ɵi_88:import5.ɵi;
  __OverlayContainer_89:any;
  __ScrollDispatcher_90:any;
  __ɵh_91:any;
  __ɵk_92:import6.ɵk;
  __Overlay_93:import6.Overlay;
  __Platform_94:import6.Platform;
  __InteractivityChecker_95:import6.InteractivityChecker;
  __FocusTrapFactory_96:import6.FocusTrapFactory;
  __LiveAnnouncer_97:any;
  __MdDialog_98:import6.MdDialog;
  __FocusOriginMonitor_99:any;
  __UniqueSelectionDispatcher_100:any;
  __BrowserXhr_101:import7.BrowserXhr;
  __ResponseOptions_102:import7.BaseResponseOptions;
  __XSRFStrategy_103:any;
  __XHRBackend_104:import7.XHRBackend;
  __RequestOptions_105:import7.BaseRequestOptions;
  __Http_106:any;
  __MdIconRegistry_107:any;
  __MdSnackBar_108:import6.MdSnackBar;
  __ActivatedRoute_109:any;
  __NoPreloading_110:import3.NoPreloading;
  __PreloadingStrategy_111:any;
  __RouterPreloader_112:import3.RouterPreloader;
  __PreloadAllModules_113:import3.PreloadAllModules;
  __ROUTER_INITIALIZER_114:any;
  __Dispatcher_115:import16.Dispatcher;
  __REDUX_DEVTOOLS_EXTENSION_116:any;
  __Reducer_117:any;
  __State_118:any;
  __Store_119:any;
  __APP_BOOTSTRAP_LISTENER_120:any[];
  __D3Service_121:import17.D3Service;
  __DialogsService_122:import18.DialogsService;
  __DevtoolsExtension_123:import19.DevtoolsExtension;
  __DevtoolsDispatcher_124:import20.DevtoolsDispatcher;
  __INITIAL_STATE_125:any;
  __INITIAL_REDUCER_126:any;
  __INITIAL_REDUCER_127:any;
  __INITIAL_STATE_128:any;
  _INITIAL_OPTIONS_129:any;
  __STORE_DEVTOOLS_CONFIG_130:any;
  __StoreDevtools_131:import20.StoreDevtools;
  __ErrorHandlerService_132:import21.ErrorHandlerService;
  constructor(parent:import0.Injector) {
    super(parent,[
      import22.MdDialogContainerNgFactory,
      import22.MdSnackBarContainerNgFactory,
      import22.SimpleSnackBarNgFactory,
      import22.TooltipComponentNgFactory,
      import23.InstructionComponentNgFactory,
      import24.ModelingComponentNgFactory,
      import25.Page404ComponentNgFactory,
      import26.ModalWindowComponentNgFactory,
      import27.AppComponentNgFactory
    ]
    ,[import27.AppComponentNgFactory]);
  }
  get _LOCALE_ID_68():any {
    if ((this.__LOCALE_ID_68 == null)) { (this.__LOCALE_ID_68 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_68;
  }
  get _NgLocalization_69():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_69 == null)) { (this.__NgLocalization_69 = new import2.NgLocaleLocalization(this._LOCALE_ID_68)); }
    return this.__NgLocalization_69;
  }
  get _APP_ID_70():any {
    if ((this.__APP_ID_70 == null)) { (this.__APP_ID_70 = import0.ɵg()); }
    return this.__APP_ID_70;
  }
  get _IterableDiffers_71():any {
    if ((this.__IterableDiffers_71 == null)) { (this.__IterableDiffers_71 = import0.ɵl()); }
    return this.__IterableDiffers_71;
  }
  get _KeyValueDiffers_72():any {
    if ((this.__KeyValueDiffers_72 == null)) { (this.__KeyValueDiffers_72 = import0.ɵm()); }
    return this.__KeyValueDiffers_72;
  }
  get _DomSanitizer_73():import4.ɵe {
    if ((this.__DomSanitizer_73 == null)) { (this.__DomSanitizer_73 = new import4.ɵe(this.parent.get(import4.DOCUMENT))); }
    return this.__DomSanitizer_73;
  }
  get _Sanitizer_74():any {
    if ((this.__Sanitizer_74 == null)) { (this.__Sanitizer_74 = this._DomSanitizer_73); }
    return this.__Sanitizer_74;
  }
  get _HAMMER_GESTURE_CONFIG_75():import15.HammerConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_75 == null)) { (this.__HAMMER_GESTURE_CONFIG_75 = new import15.HammerConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_75;
  }
  get _EVENT_MANAGER_PLUGINS_76():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_76 == null)) { (this.__EVENT_MANAGER_PLUGINS_76 = [
      new import4.ɵDomEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵKeyEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵHammerGesturesPlugin(this.parent.get(import4.DOCUMENT),this._HAMMER_GESTURE_CONFIG_75)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_76;
  }
  get _EventManager_77():import4.EventManager {
    if ((this.__EventManager_77 == null)) { (this.__EventManager_77 = new import4.EventManager(this._EVENT_MANAGER_PLUGINS_76,this.parent.get(import0.NgZone))); }
    return this.__EventManager_77;
  }
  get _ɵDomSharedStylesHost_78():import4.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_78 == null)) { (this.__ɵDomSharedStylesHost_78 = new import4.ɵDomSharedStylesHost(this.parent.get(import4.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_78;
  }
  get _ɵDomRendererFactory2_79():import4.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_79 == null)) { (this.__ɵDomRendererFactory2_79 = new import4.ɵDomRendererFactory2(this._EventManager_77,this._ɵDomSharedStylesHost_78)); }
    return this.__ɵDomRendererFactory2_79;
  }
  get _AnimationDriver_80():any {
    if ((this.__AnimationDriver_80 == null)) { (this.__AnimationDriver_80 = import11.ɵb()); }
    return this.__AnimationDriver_80;
  }
  get _ɵAnimationStyleNormalizer_81():any {
    if ((this.__ɵAnimationStyleNormalizer_81 == null)) { (this.__ɵAnimationStyleNormalizer_81 = import11.ɵc()); }
    return this.__ɵAnimationStyleNormalizer_81;
  }
  get _ɵAnimationEngine_82():import11.ɵa {
    if ((this.__ɵAnimationEngine_82 == null)) { (this.__ɵAnimationEngine_82 = new import11.ɵa(this._AnimationDriver_80,this._ɵAnimationStyleNormalizer_81)); }
    return this.__ɵAnimationEngine_82;
  }
  get _RendererFactory2_83():any {
    if ((this.__RendererFactory2_83 == null)) { (this.__RendererFactory2_83 = import11.ɵd(this._ɵDomRendererFactory2_79,this._ɵAnimationEngine_82,this.parent.get(import0.NgZone))); }
    return this.__RendererFactory2_83;
  }
  get _ɵSharedStylesHost_84():any {
    if ((this.__ɵSharedStylesHost_84 == null)) { (this.__ɵSharedStylesHost_84 = this._ɵDomSharedStylesHost_78); }
    return this.__ɵSharedStylesHost_84;
  }
  get _Testability_85():import0.Testability {
    if ((this.__Testability_85 == null)) { (this.__Testability_85 = new import0.Testability(this.parent.get(import0.NgZone))); }
    return this.__Testability_85;
  }
  get _Meta_86():import4.Meta {
    if ((this.__Meta_86 == null)) { (this.__Meta_86 = new import4.Meta(this.parent.get(import4.DOCUMENT))); }
    return this.__Meta_86;
  }
  get _Title_87():import4.Title {
    if ((this.__Title_87 == null)) { (this.__Title_87 = new import4.Title(this.parent.get(import4.DOCUMENT))); }
    return this.__Title_87;
  }
  get _ɵi_88():import5.ɵi {
    if ((this.__ɵi_88 == null)) { (this.__ɵi_88 = new import5.ɵi()); }
    return this.__ɵi_88;
  }
  get _OverlayContainer_89():any {
    if ((this.__OverlayContainer_89 == null)) { (this.__OverlayContainer_89 = import6.ɵa(this.parent.get(import6.OverlayContainer,(null as any)))); }
    return this.__OverlayContainer_89;
  }
  get _ScrollDispatcher_90():any {
    if ((this.__ScrollDispatcher_90 == null)) { (this.__ScrollDispatcher_90 = import6.ɵc(this.parent.get(import6.ScrollDispatcher,(null as any)),this.parent.get(import0.NgZone))); }
    return this.__ScrollDispatcher_90;
  }
  get _ɵh_91():any {
    if ((this.__ɵh_91 == null)) { (this.__ɵh_91 = import6.ɵi(this.parent.get(import6.ɵh,(null as any)),this._ScrollDispatcher_90)); }
    return this.__ɵh_91;
  }
  get _ɵk_92():import6.ɵk {
    if ((this.__ɵk_92 == null)) { (this.__ɵk_92 = new import6.ɵk(this._ɵh_91)); }
    return this.__ɵk_92;
  }
  get _Overlay_93():import6.Overlay {
    if ((this.__Overlay_93 == null)) { (this.__Overlay_93 = new import6.Overlay(this._OverlayContainer_89,this.componentFactoryResolver,this._ɵk_92,this._ApplicationRef_7,this,this.parent.get(import0.NgZone))); }
    return this.__Overlay_93;
  }
  get _Platform_94():import6.Platform {
    if ((this.__Platform_94 == null)) { (this.__Platform_94 = new import6.Platform()); }
    return this.__Platform_94;
  }
  get _InteractivityChecker_95():import6.InteractivityChecker {
    if ((this.__InteractivityChecker_95 == null)) { (this.__InteractivityChecker_95 = new import6.InteractivityChecker(this._Platform_94)); }
    return this.__InteractivityChecker_95;
  }
  get _FocusTrapFactory_96():import6.FocusTrapFactory {
    if ((this.__FocusTrapFactory_96 == null)) { (this.__FocusTrapFactory_96 = new import6.FocusTrapFactory(this._InteractivityChecker_95,this.parent.get(import0.NgZone))); }
    return this.__FocusTrapFactory_96;
  }
  get _LiveAnnouncer_97():any {
    if ((this.__LiveAnnouncer_97 == null)) { (this.__LiveAnnouncer_97 = import6.ɵf(this.parent.get(import6.LiveAnnouncer,(null as any)),this.parent.get(import6.LIVE_ANNOUNCER_ELEMENT_TOKEN,(null as any)))); }
    return this.__LiveAnnouncer_97;
  }
  get _MdDialog_98():import6.MdDialog {
    if ((this.__MdDialog_98 == null)) { (this.__MdDialog_98 = new import6.MdDialog(this._Overlay_93,this,this.parent.get(import6.MdDialog,(null as any)))); }
    return this.__MdDialog_98;
  }
  get _FocusOriginMonitor_99():any {
    if ((this.__FocusOriginMonitor_99 == null)) { (this.__FocusOriginMonitor_99 = import6.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY(this.parent.get(import6.FocusOriginMonitor,(null as any)),this.parent.get(import0.NgZone))); }
    return this.__FocusOriginMonitor_99;
  }
  get _UniqueSelectionDispatcher_100():any {
    if ((this.__UniqueSelectionDispatcher_100 == null)) { (this.__UniqueSelectionDispatcher_100 = import6.ɵg(this.parent.get(import6.UniqueSelectionDispatcher,(null as any)))); }
    return this.__UniqueSelectionDispatcher_100;
  }
  get _BrowserXhr_101():import7.BrowserXhr {
    if ((this.__BrowserXhr_101 == null)) { (this.__BrowserXhr_101 = new import7.BrowserXhr()); }
    return this.__BrowserXhr_101;
  }
  get _ResponseOptions_102():import7.BaseResponseOptions {
    if ((this.__ResponseOptions_102 == null)) { (this.__ResponseOptions_102 = new import7.BaseResponseOptions()); }
    return this.__ResponseOptions_102;
  }
  get _XSRFStrategy_103():any {
    if ((this.__XSRFStrategy_103 == null)) { (this.__XSRFStrategy_103 = import7.ɵb()); }
    return this.__XSRFStrategy_103;
  }
  get _XHRBackend_104():import7.XHRBackend {
    if ((this.__XHRBackend_104 == null)) { (this.__XHRBackend_104 = new import7.XHRBackend(this._BrowserXhr_101,this._ResponseOptions_102,this._XSRFStrategy_103)); }
    return this.__XHRBackend_104;
  }
  get _RequestOptions_105():import7.BaseRequestOptions {
    if ((this.__RequestOptions_105 == null)) { (this.__RequestOptions_105 = new import7.BaseRequestOptions()); }
    return this.__RequestOptions_105;
  }
  get _Http_106():any {
    if ((this.__Http_106 == null)) { (this.__Http_106 = import7.ɵc(this._XHRBackend_104,this._RequestOptions_105)); }
    return this.__Http_106;
  }
  get _MdIconRegistry_107():any {
    if ((this.__MdIconRegistry_107 == null)) { (this.__MdIconRegistry_107 = import6.ICON_REGISTRY_PROVIDER_FACTORY(this.parent.get(import6.MdIconRegistry,(null as any)),this._Http_106,this._DomSanitizer_73)); }
    return this.__MdIconRegistry_107;
  }
  get _MdSnackBar_108():import6.MdSnackBar {
    if ((this.__MdSnackBar_108 == null)) { (this.__MdSnackBar_108 = new import6.MdSnackBar(this._Overlay_93,this._LiveAnnouncer_97,this.parent.get(import6.MdSnackBar,(null as any)))); }
    return this.__MdSnackBar_108;
  }
  get _ActivatedRoute_109():any {
    if ((this.__ActivatedRoute_109 == null)) { (this.__ActivatedRoute_109 = import3.ɵf(this._Router_59)); }
    return this.__ActivatedRoute_109;
  }
  get _NoPreloading_110():import3.NoPreloading {
    if ((this.__NoPreloading_110 == null)) { (this.__NoPreloading_110 = new import3.NoPreloading()); }
    return this.__NoPreloading_110;
  }
  get _PreloadingStrategy_111():any {
    if ((this.__PreloadingStrategy_111 == null)) { (this.__PreloadingStrategy_111 = this._NoPreloading_110); }
    return this.__PreloadingStrategy_111;
  }
  get _RouterPreloader_112():import3.RouterPreloader {
    if ((this.__RouterPreloader_112 == null)) { (this.__RouterPreloader_112 = new import3.RouterPreloader(this._Router_59,this._NgModuleFactoryLoader_57,this._Compiler_56,this,this._PreloadingStrategy_111)); }
    return this.__RouterPreloader_112;
  }
  get _PreloadAllModules_113():import3.PreloadAllModules {
    if ((this.__PreloadAllModules_113 == null)) { (this.__PreloadAllModules_113 = new import3.PreloadAllModules()); }
    return this.__PreloadAllModules_113;
  }
  get _ROUTER_INITIALIZER_114():any {
    if ((this.__ROUTER_INITIALIZER_114 == null)) { (this.__ROUTER_INITIALIZER_114 = import3.ɵi(this._ɵg_3)); }
    return this.__ROUTER_INITIALIZER_114;
  }
  get _Dispatcher_115():import16.Dispatcher {
    if ((this.__Dispatcher_115 == null)) { (this.__Dispatcher_115 = new import16.Dispatcher()); }
    return this.__Dispatcher_115;
  }
  get _REDUX_DEVTOOLS_EXTENSION_116():any {
    if ((this.__REDUX_DEVTOOLS_EXTENSION_116 == null)) { (this.__REDUX_DEVTOOLS_EXTENSION_116 = import14._createReduxDevtoolsExtension()); }
    return this.__REDUX_DEVTOOLS_EXTENSION_116;
  }
  get _Reducer_117():any {
    if ((this.__Reducer_117 == null)) { (this.__Reducer_117 = import14._createReducerIfExtension(this._REDUX_DEVTOOLS_EXTENSION_116,this)); }
    return this.__Reducer_117;
  }
  get _State_118():any {
    if ((this.__State_118 == null)) { (this.__State_118 = import14._createStateIfExtension(this._REDUX_DEVTOOLS_EXTENSION_116,this)); }
    return this.__State_118;
  }
  get _Store_119():any {
    if ((this.__Store_119 == null)) { (this.__Store_119 = import12._storeFactory(this._Dispatcher_115,this._Reducer_117,this._State_118)); }
    return this.__Store_119;
  }
  get _APP_BOOTSTRAP_LISTENER_120():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_120 == null)) { (this.__APP_BOOTSTRAP_LISTENER_120 = [
      this._ROUTER_INITIALIZER_114,
      import13.setupRouterStore(this._Router_59,this._Location_55,this._Dispatcher_115,this._Store_119)
    ]
    ); }
    return this.__APP_BOOTSTRAP_LISTENER_120;
  }
  get _D3Service_121():import17.D3Service {
    if ((this.__D3Service_121 == null)) { (this.__D3Service_121 = new import17.D3Service()); }
    return this.__D3Service_121;
  }
  get _DialogsService_122():import18.DialogsService {
    if ((this.__DialogsService_122 == null)) { (this.__DialogsService_122 = new import18.DialogsService()); }
    return this.__DialogsService_122;
  }
  get _DevtoolsExtension_123():import19.DevtoolsExtension {
    if ((this.__DevtoolsExtension_123 == null)) { (this.__DevtoolsExtension_123 = new import19.DevtoolsExtension(this._REDUX_DEVTOOLS_EXTENSION_116)); }
    return this.__DevtoolsExtension_123;
  }
  get _DevtoolsDispatcher_124():import20.DevtoolsDispatcher {
    if ((this.__DevtoolsDispatcher_124 == null)) { (this.__DevtoolsDispatcher_124 = new import20.DevtoolsDispatcher()); }
    return this.__DevtoolsDispatcher_124;
  }
  get _INITIAL_REDUCER_127():any {
    if ((this.__INITIAL_REDUCER_127 == null)) { (this.__INITIAL_REDUCER_127 = import12._initialReducerFactory(this.__INITIAL_REDUCER_126)); }
    return this.__INITIAL_REDUCER_127;
  }
  get _INITIAL_STATE_128():any {
    if ((this.__INITIAL_STATE_128 == null)) { (this.__INITIAL_STATE_128 = import12._initialStateFactory(this.__INITIAL_STATE_125,this._INITIAL_REDUCER_127)); }
    return this.__INITIAL_STATE_128;
  }
  get _STORE_DEVTOOLS_CONFIG_130():any {
    if ((this.__STORE_DEVTOOLS_CONFIG_130 == null)) { (this.__STORE_DEVTOOLS_CONFIG_130 = import14._createOptions(this._INITIAL_OPTIONS_129)); }
    return this.__STORE_DEVTOOLS_CONFIG_130;
  }
  get _StoreDevtools_131():import20.StoreDevtools {
    if ((this.__StoreDevtools_131 == null)) { (this.__StoreDevtools_131 = new import20.StoreDevtools(this._DevtoolsDispatcher_124,this._Dispatcher_115,this._Reducer_117,this._DevtoolsExtension_123,this._INITIAL_STATE_128,this._STORE_DEVTOOLS_CONFIG_130)); }
    return this.__StoreDevtools_131;
  }
  get _ErrorHandlerService_132():import21.ErrorHandlerService {
    if ((this.__ErrorHandlerService_132 == null)) { (this.__ErrorHandlerService_132 = new import21.ErrorHandlerService()); }
    return this.__ErrorHandlerService_132;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ErrorHandler_1 = import4.ɵa();
    this._NgProbeToken_2 = [import3.ɵb()];
    this._ɵg_3 = new import3.ɵg(this);
    this._APP_INITIALIZER_4 = [
      import0.ɵo,
      import4.ɵc(this.parent.get(import4.NgProbeToken,(null as any)),this._NgProbeToken_2),
      import3.ɵh(this._ɵg_3)
    ]
    ;
    this._ApplicationInitStatus_5 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_4);
    this._ɵf_6 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_1,this.componentFactoryResolver,this._ApplicationInitStatus_5);
    this._ApplicationRef_7 = this._ɵf_6;
    this._ApplicationModule_8 = new import0.ApplicationModule(this._ApplicationRef_7);
    this._BrowserModule_9 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._ɵba_10 = new import5.ɵba();
    this._FormsModule_11 = new import5.FormsModule();
    this._PortalModule_12 = new import6.PortalModule();
    this._OverlayModule_13 = new import6.OverlayModule();
    this._PlatformModule_14 = new import6.PlatformModule();
    this._A11yModule_15 = new import6.A11yModule();
    this._CompatibilityModule_16 = new import6.CompatibilityModule(this.parent.get(import4.DOCUMENT,(null as any)));
    this._MdDialogModule_17 = new import6.MdDialogModule();
    this._MdRippleModule_18 = new import6.MdRippleModule();
    this._MdSelectionModule_19 = new import6.MdSelectionModule();
    this._MdOptionModule_20 = new import6.MdOptionModule();
    this._MdAutocompleteModule_21 = new import6.MdAutocompleteModule();
    this._StyleModule_22 = new import6.StyleModule();
    this._MdButtonModule_23 = new import6.MdButtonModule();
    this._MdButtonToggleModule_24 = new import6.MdButtonToggleModule();
    this._MdCardModule_25 = new import6.MdCardModule();
    this._MdChipsModule_26 = new import6.MdChipsModule();
    this._MdCheckboxModule_27 = new import6.MdCheckboxModule();
    this._MdLineModule_28 = new import6.MdLineModule();
    this._MdGridListModule_29 = new import6.MdGridListModule();
    this._HttpModule_30 = new import7.HttpModule();
    this._MdIconModule_31 = new import6.MdIconModule();
    this._MdInputModule_32 = new import6.MdInputModule();
    this._MdListModule_33 = new import6.MdListModule();
    this._MdMenuModule_34 = new import6.MdMenuModule();
    this._MdProgressBarModule_35 = new import6.MdProgressBarModule();
    this._MdProgressSpinnerModule_36 = new import6.MdProgressSpinnerModule();
    this._MdRadioModule_37 = new import6.MdRadioModule();
    this._MdSelectModule_38 = new import6.MdSelectModule();
    this._MdSidenavModule_39 = new import6.MdSidenavModule();
    this._RtlModule_40 = new import6.RtlModule();
    this._MdSliderModule_41 = new import6.MdSliderModule();
    this._MdSlideToggleModule_42 = new import6.MdSlideToggleModule();
    this._MdSnackBarModule_43 = new import6.MdSnackBarModule();
    this._ObserveContentModule_44 = new import6.ObserveContentModule();
    this._MdTabsModule_45 = new import6.MdTabsModule();
    this._MdToolbarModule_46 = new import6.MdToolbarModule();
    this._MdTooltipModule_47 = new import6.MdTooltipModule();
    this._MaterialModule_48 = new import6.MaterialModule();
    this._SharedModule_49 = new import8.SharedModule();
    this._ɵa_50 = import3.ɵd(this.parent.get(import3.Router,(null as any)));
    this._UrlSerializer_51 = new import3.DefaultUrlSerializer();
    this._RouterOutletMap_52 = new import3.RouterOutletMap();
    this._ROUTER_CONFIGURATION_53 = {useHash: true};
    this._LocationStrategy_54 = import3.ɵc(this.parent.get(import2.PlatformLocation),this.parent.get(import2.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_53);
    this._Location_55 = new import2.Location(this._LocationStrategy_54);
    this._Compiler_56 = new import0.Compiler();
    this._NgModuleFactoryLoader_57 = new import0.SystemJsNgModuleLoader(this._Compiler_56,this.parent.get(import0.SystemJsNgModuleLoaderConfig,(null as any)));
      this._ROUTES_58 = [[
        {
          path: '',
          redirectTo: 'instruction',
          pathMatch: 'full'
        }
        ,
        {
          path: 'instruction',
          component: import28.InstructionComponent
        }
        ,
        {
          path: 'modeling',
          component: import29.ModelingComponent
        }
        ,
        {
          path: '**',
          component: import30.Page404Component
        }

      ]
    ];
    this._Router_59 = import3.ɵe(this._ApplicationRef_7,this._UrlSerializer_51,this._RouterOutletMap_52,this._Location_55,this,this._NgModuleFactoryLoader_57,this._Compiler_56,this._ROUTES_58,this._ROUTER_CONFIGURATION_53,this.parent.get(import3.UrlHandlingStrategy,(null as any)),this.parent.get(import3.RouteReuseStrategy,(null as any)));
    this._RouterModule_60 = new import3.RouterModule(this._ɵa_50,this._Router_59);
    this._AppRoutingModule_61 = new import9.AppRoutingModule();
    this._CoreModule_62 = new import10.CoreModule();
    this._BrowserAnimationsModule_63 = new import11.BrowserAnimationsModule();
    this._StoreModule_64 = new import12.StoreModule();
    this._RouterStoreModule_65 = new import13.RouterStoreModule();
    this._StoreDevtoolsModule_66 = new import14.StoreDevtoolsModule();
    this._AppModule_67 = new import1.AppModule();
    this.__INITIAL_STATE_125 = (undefined as any);
    this.__INITIAL_REDUCER_126 = import31.reducer;
    this._INITIAL_OPTIONS_129 = {maxAge: 25};
    return this._AppModule_67;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_1; }
    if ((token === import0.NgProbeToken)) { return this._NgProbeToken_2; }
    if ((token === import3.ɵg)) { return this._ɵg_3; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_4; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_5; }
    if ((token === import0.ɵf)) { return this._ɵf_6; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_7; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_8; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_9; }
    if ((token === import5.ɵba)) { return this._ɵba_10; }
    if ((token === import5.FormsModule)) { return this._FormsModule_11; }
    if ((token === import6.PortalModule)) { return this._PortalModule_12; }
    if ((token === import6.OverlayModule)) { return this._OverlayModule_13; }
    if ((token === import6.PlatformModule)) { return this._PlatformModule_14; }
    if ((token === import6.A11yModule)) { return this._A11yModule_15; }
    if ((token === import6.CompatibilityModule)) { return this._CompatibilityModule_16; }
    if ((token === import6.MdDialogModule)) { return this._MdDialogModule_17; }
    if ((token === import6.MdRippleModule)) { return this._MdRippleModule_18; }
    if ((token === import6.MdSelectionModule)) { return this._MdSelectionModule_19; }
    if ((token === import6.MdOptionModule)) { return this._MdOptionModule_20; }
    if ((token === import6.MdAutocompleteModule)) { return this._MdAutocompleteModule_21; }
    if ((token === import6.StyleModule)) { return this._StyleModule_22; }
    if ((token === import6.MdButtonModule)) { return this._MdButtonModule_23; }
    if ((token === import6.MdButtonToggleModule)) { return this._MdButtonToggleModule_24; }
    if ((token === import6.MdCardModule)) { return this._MdCardModule_25; }
    if ((token === import6.MdChipsModule)) { return this._MdChipsModule_26; }
    if ((token === import6.MdCheckboxModule)) { return this._MdCheckboxModule_27; }
    if ((token === import6.MdLineModule)) { return this._MdLineModule_28; }
    if ((token === import6.MdGridListModule)) { return this._MdGridListModule_29; }
    if ((token === import7.HttpModule)) { return this._HttpModule_30; }
    if ((token === import6.MdIconModule)) { return this._MdIconModule_31; }
    if ((token === import6.MdInputModule)) { return this._MdInputModule_32; }
    if ((token === import6.MdListModule)) { return this._MdListModule_33; }
    if ((token === import6.MdMenuModule)) { return this._MdMenuModule_34; }
    if ((token === import6.MdProgressBarModule)) { return this._MdProgressBarModule_35; }
    if ((token === import6.MdProgressSpinnerModule)) { return this._MdProgressSpinnerModule_36; }
    if ((token === import6.MdRadioModule)) { return this._MdRadioModule_37; }
    if ((token === import6.MdSelectModule)) { return this._MdSelectModule_38; }
    if ((token === import6.MdSidenavModule)) { return this._MdSidenavModule_39; }
    if ((token === import6.RtlModule)) { return this._RtlModule_40; }
    if ((token === import6.MdSliderModule)) { return this._MdSliderModule_41; }
    if ((token === import6.MdSlideToggleModule)) { return this._MdSlideToggleModule_42; }
    if ((token === import6.MdSnackBarModule)) { return this._MdSnackBarModule_43; }
    if ((token === import6.ObserveContentModule)) { return this._ObserveContentModule_44; }
    if ((token === import6.MdTabsModule)) { return this._MdTabsModule_45; }
    if ((token === import6.MdToolbarModule)) { return this._MdToolbarModule_46; }
    if ((token === import6.MdTooltipModule)) { return this._MdTooltipModule_47; }
    if ((token === import6.MaterialModule)) { return this._MaterialModule_48; }
    if ((token === import8.SharedModule)) { return this._SharedModule_49; }
    if ((token === import3.ɵa)) { return this._ɵa_50; }
    if ((token === import3.UrlSerializer)) { return this._UrlSerializer_51; }
    if ((token === import3.RouterOutletMap)) { return this._RouterOutletMap_52; }
    if ((token === import3.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_53; }
    if ((token === import2.LocationStrategy)) { return this._LocationStrategy_54; }
    if ((token === import2.Location)) { return this._Location_55; }
    if ((token === import0.Compiler)) { return this._Compiler_56; }
    if ((token === import0.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_57; }
    if ((token === import3.ROUTES)) { return this._ROUTES_58; }
    if ((token === import3.Router)) { return this._Router_59; }
    if ((token === import3.RouterModule)) { return this._RouterModule_60; }
    if ((token === import9.AppRoutingModule)) { return this._AppRoutingModule_61; }
    if ((token === import10.CoreModule)) { return this._CoreModule_62; }
    if ((token === import11.BrowserAnimationsModule)) { return this._BrowserAnimationsModule_63; }
    if ((token === import12.StoreModule)) { return this._StoreModule_64; }
    if ((token === import13.RouterStoreModule)) { return this._RouterStoreModule_65; }
    if ((token === import14.StoreDevtoolsModule)) { return this._StoreDevtoolsModule_66; }
    if ((token === import1.AppModule)) { return this._AppModule_67; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_68; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_69; }
    if ((token === import0.APP_ID)) { return this._APP_ID_70; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_71; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_72; }
    if ((token === import4.DomSanitizer)) { return this._DomSanitizer_73; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_74; }
    if ((token === import4.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_75; }
    if ((token === import4.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_76; }
    if ((token === import4.EventManager)) { return this._EventManager_77; }
    if ((token === import4.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_78; }
    if ((token === import4.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_79; }
    if ((token === import32.AnimationDriver)) { return this._AnimationDriver_80; }
    if ((token === import32.ɵAnimationStyleNormalizer)) { return this._ɵAnimationStyleNormalizer_81; }
    if ((token === import32.ɵAnimationEngine)) { return this._ɵAnimationEngine_82; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_83; }
    if ((token === import4.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_84; }
    if ((token === import0.Testability)) { return this._Testability_85; }
    if ((token === import4.Meta)) { return this._Meta_86; }
    if ((token === import4.Title)) { return this._Title_87; }
    if ((token === import5.ɵi)) { return this._ɵi_88; }
    if ((token === import6.OverlayContainer)) { return this._OverlayContainer_89; }
    if ((token === import6.ScrollDispatcher)) { return this._ScrollDispatcher_90; }
    if ((token === import6.ɵh)) { return this._ɵh_91; }
    if ((token === import6.ɵk)) { return this._ɵk_92; }
    if ((token === import6.Overlay)) { return this._Overlay_93; }
    if ((token === import6.Platform)) { return this._Platform_94; }
    if ((token === import6.InteractivityChecker)) { return this._InteractivityChecker_95; }
    if ((token === import6.FocusTrapFactory)) { return this._FocusTrapFactory_96; }
    if ((token === import6.LiveAnnouncer)) { return this._LiveAnnouncer_97; }
    if ((token === import6.MdDialog)) { return this._MdDialog_98; }
    if ((token === import6.FocusOriginMonitor)) { return this._FocusOriginMonitor_99; }
    if ((token === import6.UniqueSelectionDispatcher)) { return this._UniqueSelectionDispatcher_100; }
    if ((token === import7.BrowserXhr)) { return this._BrowserXhr_101; }
    if ((token === import7.ResponseOptions)) { return this._ResponseOptions_102; }
    if ((token === import7.XSRFStrategy)) { return this._XSRFStrategy_103; }
    if ((token === import7.XHRBackend)) { return this._XHRBackend_104; }
    if ((token === import7.RequestOptions)) { return this._RequestOptions_105; }
    if ((token === import7.Http)) { return this._Http_106; }
    if ((token === import6.MdIconRegistry)) { return this._MdIconRegistry_107; }
    if ((token === import6.MdSnackBar)) { return this._MdSnackBar_108; }
    if ((token === import3.ActivatedRoute)) { return this._ActivatedRoute_109; }
    if ((token === import3.NoPreloading)) { return this._NoPreloading_110; }
    if ((token === import3.PreloadingStrategy)) { return this._PreloadingStrategy_111; }
    if ((token === import3.RouterPreloader)) { return this._RouterPreloader_112; }
    if ((token === import3.PreloadAllModules)) { return this._PreloadAllModules_113; }
    if ((token === import3.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_114; }
    if ((token === import16.Dispatcher)) { return this._Dispatcher_115; }
    if ((token === import19.REDUX_DEVTOOLS_EXTENSION)) { return this._REDUX_DEVTOOLS_EXTENSION_116; }
    if ((token === import33.Reducer)) { return this._Reducer_117; }
    if ((token === import34.State)) { return this._State_118; }
    if ((token === import35.Store)) { return this._Store_119; }
    if ((token === import0.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_120; }
    if ((token === import17.D3Service)) { return this._D3Service_121; }
    if ((token === import18.DialogsService)) { return this._DialogsService_122; }
    if ((token === import19.DevtoolsExtension)) { return this._DevtoolsExtension_123; }
    if ((token === import20.DevtoolsDispatcher)) { return this._DevtoolsDispatcher_124; }
    if ((token === import12._INITIAL_STATE)) { return this.__INITIAL_STATE_125; }
    if ((token === import12._INITIAL_REDUCER)) { return this.__INITIAL_REDUCER_126; }
    if ((token === import12.INITIAL_REDUCER)) { return this._INITIAL_REDUCER_127; }
    if ((token === import12.INITIAL_STATE)) { return this._INITIAL_STATE_128; }
    if ((token === import36.INITIAL_OPTIONS)) { return this._INITIAL_OPTIONS_129; }
    if ((token === import36.STORE_DEVTOOLS_CONFIG)) { return this._STORE_DEVTOOLS_CONFIG_130; }
    if ((token === import20.StoreDevtools)) { return this._StoreDevtools_131; }
    if ((token === import21.ErrorHandlerService)) { return this._ErrorHandlerService_132; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_6.ngOnDestroy();
    (this.__ɵDomSharedStylesHost_78 && this._ɵDomSharedStylesHost_78.ngOnDestroy());
    (this.__RouterPreloader_112 && this._RouterPreloader_112.ngOnDestroy());
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory<any>(AppModuleInjector,import1.AppModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvaW50ZXJuZXQvRG9jdW1lbnRzL0dpdEh1Yi9hbmd1bGFyMi9nZW5fZHJpZnQtbmdyeC00LXJjMy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9pbnRlcm5ldC9Eb2N1bWVudHMvR2l0SHViL2FuZ3VsYXIyL2dlbl9kcmlmdC1uZ3J4LTQtcmMzL2FwcC9hcHAubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
