/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../app/core/page.404.component/page.404.component';
const styles_Page404Component:any[] = ['.page-404[_ngcontent-%COMP%]{color: #b43232; font-size: 34px}'];
export const RenderType_Page404Component:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_Page404Component,
  data: {}
}
);
export function View_Page404Component_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(2,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',[[
        'class',
        'page-404'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['404. Page not found!']))
  ]
  ,(null as any),(null as any));
}
function View_Page404Component_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'page-404',([] as any[]),(null as any),(null as any),(null as any),View_Page404Component_0,RenderType_Page404Component)),
    import0.ɵdid(24576,(null as any),0,import1.Page404Component,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const Page404ComponentNgFactory:import0.ComponentFactory<import1.Page404Component> = import0.ɵccf('page-404',import1.Page404Component,View_Page404Component_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvaW50ZXJuZXQvRG9jdW1lbnRzL0dpdEh1Yi9hbmd1bGFyMi9nZW5fZHJpZnQtbmdyeC00LXJjMy9hcHAvY29yZS9wYWdlLjQwNC5jb21wb25lbnQvcGFnZS40MDQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL2ludGVybmV0L0RvY3VtZW50cy9HaXRIdWIvYW5ndWxhcjIvZ2VuX2RyaWZ0LW5ncngtNC1yYzMvYXBwL2NvcmUvcGFnZS40MDQuY29tcG9uZW50L3BhZ2UuNDA0LmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL2ludGVybmV0L0RvY3VtZW50cy9HaXRIdWIvYW5ndWxhcjIvZ2VuX2RyaWZ0LW5ncngtNC1yYzMvYXBwL2NvcmUvcGFnZS40MDQuY29tcG9uZW50L3BhZ2UuNDA0LmNvbXBvbmVudC50cy5QYWdlNDA0Q29tcG9uZW50Lmh0bWwiLCJuZzovLy9DOi9Vc2Vycy9pbnRlcm5ldC9Eb2N1bWVudHMvR2l0SHViL2FuZ3VsYXIyL2dlbl9kcmlmdC1uZ3J4LTQtcmMzL2FwcC9jb3JlL3BhZ2UuNDA0LmNvbXBvbmVudC9wYWdlLjQwNC5jb21wb25lbnQudHMuUGFnZTQwNENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMSBjbGFzcz1cInBhZ2UtNDA0XCI+NDA0LiBQYWdlIG5vdCBmb3VuZCE8L2gxPiIsIjxwYWdlLTQwND48L3BhZ2UtNDA0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7TUNBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQXFCOzs7Ozs7SUNBckI7Z0JBQUE7Ozs7In0=
