/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../app/core/core.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/forms';
import * as import4 from '@angular/router';
import * as import5 from '../../../app/core/app-routing.module';
import * as import6 from '@angular/material';
import * as import7 from '@angular/http';
import * as import8 from '../../../app/shared/shared.module';
import * as import9 from '../../../app/services/d3.service';
import * as import10 from '../../../app/services/dialogs.service';
import * as import11 from './inctruction.component/instruction.component.ngfactory';
import * as import12 from './modeling.component/modeling.component.ngfactory';
import * as import13 from './page.404.component/page.404.component.ngfactory';
import * as import14 from '../../node_modules/@angular/material/typings/index.ngfactory';
import * as import15 from '../shared/modal_window.component/modal_window.component.ngfactory';
import * as import16 from '@angular/platform-browser';
import * as import17 from '../../../app/core/inctruction.component/instruction.component';
import * as import18 from '../../../app/core/modeling.component/modeling.component';
import * as import19 from '../../../app/core/page.404.component/page.404.component';
class CoreModuleInjector extends import0.ɵNgModuleInjector<import1.CoreModule> {
  _CommonModule_0:import2.CommonModule;
  _ɵba_1:import3.ɵba;
  _FormsModule_2:import3.FormsModule;
  _ɵa_3:any;
  _UrlSerializer_4:import4.DefaultUrlSerializer;
  _RouterOutletMap_5:import4.RouterOutletMap;
  _ROUTER_CONFIGURATION_6:any;
  _LocationStrategy_7:any;
  _Location_8:import2.Location;
  _NgModuleFactoryLoader_9:import0.SystemJsNgModuleLoader;
  _ROUTES_10:any[];
  _Router_11:any;
  _RouterModule_12:import4.RouterModule;
  _AppRoutingModule_13:import5.AppRoutingModule;
  _PortalModule_14:import6.PortalModule;
  _OverlayModule_15:import6.OverlayModule;
  _PlatformModule_16:import6.PlatformModule;
  _A11yModule_17:import6.A11yModule;
  _CompatibilityModule_18:import6.CompatibilityModule;
  _MdDialogModule_19:import6.MdDialogModule;
  _MdRippleModule_20:import6.MdRippleModule;
  _MdSelectionModule_21:import6.MdSelectionModule;
  _MdOptionModule_22:import6.MdOptionModule;
  _MdAutocompleteModule_23:import6.MdAutocompleteModule;
  _StyleModule_24:import6.StyleModule;
  _MdButtonModule_25:import6.MdButtonModule;
  _MdButtonToggleModule_26:import6.MdButtonToggleModule;
  _MdCardModule_27:import6.MdCardModule;
  _MdChipsModule_28:import6.MdChipsModule;
  _MdCheckboxModule_29:import6.MdCheckboxModule;
  _MdLineModule_30:import6.MdLineModule;
  _MdGridListModule_31:import6.MdGridListModule;
  _HttpModule_32:import7.HttpModule;
  _MdIconModule_33:import6.MdIconModule;
  _MdInputModule_34:import6.MdInputModule;
  _MdListModule_35:import6.MdListModule;
  _MdMenuModule_36:import6.MdMenuModule;
  _MdProgressBarModule_37:import6.MdProgressBarModule;
  _MdProgressSpinnerModule_38:import6.MdProgressSpinnerModule;
  _MdRadioModule_39:import6.MdRadioModule;
  _MdSelectModule_40:import6.MdSelectModule;
  _MdSidenavModule_41:import6.MdSidenavModule;
  _RtlModule_42:import6.RtlModule;
  _MdSliderModule_43:import6.MdSliderModule;
  _MdSlideToggleModule_44:import6.MdSlideToggleModule;
  _MdSnackBarModule_45:import6.MdSnackBarModule;
  _ObserveContentModule_46:import6.ObserveContentModule;
  _MdTabsModule_47:import6.MdTabsModule;
  _MdToolbarModule_48:import6.MdToolbarModule;
  _MdTooltipModule_49:import6.MdTooltipModule;
  _MaterialModule_50:import6.MaterialModule;
  _SharedModule_51:import8.SharedModule;
  _CoreModule_52:import1.CoreModule;
  __NgLocalization_53:import2.NgLocaleLocalization;
  __ɵi_54:import3.ɵi;
  __ActivatedRoute_55:any;
  __NoPreloading_56:import4.NoPreloading;
  __PreloadingStrategy_57:any;
  __RouterPreloader_58:import4.RouterPreloader;
  __PreloadAllModules_59:import4.PreloadAllModules;
  __NgProbeToken_60:any[];
  __ɵg_61:import4.ɵg;
  __APP_INITIALIZER_62:any[];
  __ROUTER_INITIALIZER_63:any;
  __APP_BOOTSTRAP_LISTENER_64:any[];
  __OverlayContainer_65:any;
  __ScrollDispatcher_66:any;
  __ɵh_67:any;
  __ɵk_68:import6.ɵk;
  __Overlay_69:import6.Overlay;
  __Platform_70:import6.Platform;
  __InteractivityChecker_71:import6.InteractivityChecker;
  __FocusTrapFactory_72:import6.FocusTrapFactory;
  __LiveAnnouncer_73:any;
  __MdDialog_74:import6.MdDialog;
  __FocusOriginMonitor_75:any;
  __UniqueSelectionDispatcher_76:any;
  __BrowserXhr_77:import7.BrowserXhr;
  __ResponseOptions_78:import7.BaseResponseOptions;
  __XSRFStrategy_79:any;
  __XHRBackend_80:import7.XHRBackend;
  __RequestOptions_81:import7.BaseRequestOptions;
  __Http_82:any;
  __MdIconRegistry_83:any;
  __HAMMER_GESTURE_CONFIG_84:import6.GestureConfig;
  __MdSnackBar_85:import6.MdSnackBar;
  __D3Service_86:import9.D3Service;
  __DialogsService_87:import10.DialogsService;
  constructor(parent:import0.Injector) {
    super(parent,[
      import11.InstructionComponentNgFactory,
      import12.ModelingComponentNgFactory,
      import13.Page404ComponentNgFactory,
      import14.MdDialogContainerNgFactory,
      import14.MdSnackBarContainerNgFactory,
      import14.SimpleSnackBarNgFactory,
      import14.TooltipComponentNgFactory,
      import15.ModalWindowComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _NgLocalization_53():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_53 == null)) { (this.__NgLocalization_53 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_53;
  }
  get _ɵi_54():import3.ɵi {
    if ((this.__ɵi_54 == null)) { (this.__ɵi_54 = new import3.ɵi()); }
    return this.__ɵi_54;
  }
  get _ActivatedRoute_55():any {
    if ((this.__ActivatedRoute_55 == null)) { (this.__ActivatedRoute_55 = import4.ɵf(this._Router_11)); }
    return this.__ActivatedRoute_55;
  }
  get _NoPreloading_56():import4.NoPreloading {
    if ((this.__NoPreloading_56 == null)) { (this.__NoPreloading_56 = new import4.NoPreloading()); }
    return this.__NoPreloading_56;
  }
  get _PreloadingStrategy_57():any {
    if ((this.__PreloadingStrategy_57 == null)) { (this.__PreloadingStrategy_57 = this._NoPreloading_56); }
    return this.__PreloadingStrategy_57;
  }
  get _RouterPreloader_58():import4.RouterPreloader {
    if ((this.__RouterPreloader_58 == null)) { (this.__RouterPreloader_58 = new import4.RouterPreloader(this._Router_11,this._NgModuleFactoryLoader_9,this.parent.get(import0.Compiler),this,this._PreloadingStrategy_57)); }
    return this.__RouterPreloader_58;
  }
  get _PreloadAllModules_59():import4.PreloadAllModules {
    if ((this.__PreloadAllModules_59 == null)) { (this.__PreloadAllModules_59 = new import4.PreloadAllModules()); }
    return this.__PreloadAllModules_59;
  }
  get _NgProbeToken_60():any[] {
    if ((this.__NgProbeToken_60 == null)) { (this.__NgProbeToken_60 = [import4.ɵb()]); }
    return this.__NgProbeToken_60;
  }
  get _ɵg_61():import4.ɵg {
    if ((this.__ɵg_61 == null)) { (this.__ɵg_61 = new import4.ɵg(this)); }
    return this.__ɵg_61;
  }
  get _APP_INITIALIZER_62():any[] {
    if ((this.__APP_INITIALIZER_62 == null)) { (this.__APP_INITIALIZER_62 = [import4.ɵh(this._ɵg_61)]); }
    return this.__APP_INITIALIZER_62;
  }
  get _ROUTER_INITIALIZER_63():any {
    if ((this.__ROUTER_INITIALIZER_63 == null)) { (this.__ROUTER_INITIALIZER_63 = import4.ɵi(this._ɵg_61)); }
    return this.__ROUTER_INITIALIZER_63;
  }
  get _APP_BOOTSTRAP_LISTENER_64():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_64 == null)) { (this.__APP_BOOTSTRAP_LISTENER_64 = [this._ROUTER_INITIALIZER_63]); }
    return this.__APP_BOOTSTRAP_LISTENER_64;
  }
  get _OverlayContainer_65():any {
    if ((this.__OverlayContainer_65 == null)) { (this.__OverlayContainer_65 = import6.ɵa(this.parent.get(import6.OverlayContainer,(null as any)))); }
    return this.__OverlayContainer_65;
  }
  get _ScrollDispatcher_66():any {
    if ((this.__ScrollDispatcher_66 == null)) { (this.__ScrollDispatcher_66 = import6.ɵc(this.parent.get(import6.ScrollDispatcher,(null as any)),this.parent.get(import0.NgZone))); }
    return this.__ScrollDispatcher_66;
  }
  get _ɵh_67():any {
    if ((this.__ɵh_67 == null)) { (this.__ɵh_67 = import6.ɵi(this.parent.get(import6.ɵh,(null as any)),this._ScrollDispatcher_66)); }
    return this.__ɵh_67;
  }
  get _ɵk_68():import6.ɵk {
    if ((this.__ɵk_68 == null)) { (this.__ɵk_68 = new import6.ɵk(this._ɵh_67)); }
    return this.__ɵk_68;
  }
  get _Overlay_69():import6.Overlay {
    if ((this.__Overlay_69 == null)) { (this.__Overlay_69 = new import6.Overlay(this._OverlayContainer_65,this.componentFactoryResolver,this._ɵk_68,this.parent.get(import0.ApplicationRef),this,this.parent.get(import0.NgZone))); }
    return this.__Overlay_69;
  }
  get _Platform_70():import6.Platform {
    if ((this.__Platform_70 == null)) { (this.__Platform_70 = new import6.Platform()); }
    return this.__Platform_70;
  }
  get _InteractivityChecker_71():import6.InteractivityChecker {
    if ((this.__InteractivityChecker_71 == null)) { (this.__InteractivityChecker_71 = new import6.InteractivityChecker(this._Platform_70)); }
    return this.__InteractivityChecker_71;
  }
  get _FocusTrapFactory_72():import6.FocusTrapFactory {
    if ((this.__FocusTrapFactory_72 == null)) { (this.__FocusTrapFactory_72 = new import6.FocusTrapFactory(this._InteractivityChecker_71,this.parent.get(import0.NgZone))); }
    return this.__FocusTrapFactory_72;
  }
  get _LiveAnnouncer_73():any {
    if ((this.__LiveAnnouncer_73 == null)) { (this.__LiveAnnouncer_73 = import6.ɵf(this.parent.get(import6.LiveAnnouncer,(null as any)),this.parent.get(import6.LIVE_ANNOUNCER_ELEMENT_TOKEN,(null as any)))); }
    return this.__LiveAnnouncer_73;
  }
  get _MdDialog_74():import6.MdDialog {
    if ((this.__MdDialog_74 == null)) { (this.__MdDialog_74 = new import6.MdDialog(this._Overlay_69,this,this.parent.get(import6.MdDialog,(null as any)))); }
    return this.__MdDialog_74;
  }
  get _FocusOriginMonitor_75():any {
    if ((this.__FocusOriginMonitor_75 == null)) { (this.__FocusOriginMonitor_75 = import6.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY(this.parent.get(import6.FocusOriginMonitor,(null as any)),this.parent.get(import0.NgZone))); }
    return this.__FocusOriginMonitor_75;
  }
  get _UniqueSelectionDispatcher_76():any {
    if ((this.__UniqueSelectionDispatcher_76 == null)) { (this.__UniqueSelectionDispatcher_76 = import6.ɵg(this.parent.get(import6.UniqueSelectionDispatcher,(null as any)))); }
    return this.__UniqueSelectionDispatcher_76;
  }
  get _BrowserXhr_77():import7.BrowserXhr {
    if ((this.__BrowserXhr_77 == null)) { (this.__BrowserXhr_77 = new import7.BrowserXhr()); }
    return this.__BrowserXhr_77;
  }
  get _ResponseOptions_78():import7.BaseResponseOptions {
    if ((this.__ResponseOptions_78 == null)) { (this.__ResponseOptions_78 = new import7.BaseResponseOptions()); }
    return this.__ResponseOptions_78;
  }
  get _XSRFStrategy_79():any {
    if ((this.__XSRFStrategy_79 == null)) { (this.__XSRFStrategy_79 = import7.ɵb()); }
    return this.__XSRFStrategy_79;
  }
  get _XHRBackend_80():import7.XHRBackend {
    if ((this.__XHRBackend_80 == null)) { (this.__XHRBackend_80 = new import7.XHRBackend(this._BrowserXhr_77,this._ResponseOptions_78,this._XSRFStrategy_79)); }
    return this.__XHRBackend_80;
  }
  get _RequestOptions_81():import7.BaseRequestOptions {
    if ((this.__RequestOptions_81 == null)) { (this.__RequestOptions_81 = new import7.BaseRequestOptions()); }
    return this.__RequestOptions_81;
  }
  get _Http_82():any {
    if ((this.__Http_82 == null)) { (this.__Http_82 = import7.ɵc(this._XHRBackend_80,this._RequestOptions_81)); }
    return this.__Http_82;
  }
  get _MdIconRegistry_83():any {
    if ((this.__MdIconRegistry_83 == null)) { (this.__MdIconRegistry_83 = import6.ICON_REGISTRY_PROVIDER_FACTORY(this.parent.get(import6.MdIconRegistry,(null as any)),this._Http_82,this.parent.get(import16.DomSanitizer))); }
    return this.__MdIconRegistry_83;
  }
  get _HAMMER_GESTURE_CONFIG_84():import6.GestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_84 == null)) { (this.__HAMMER_GESTURE_CONFIG_84 = new import6.GestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_84;
  }
  get _MdSnackBar_85():import6.MdSnackBar {
    if ((this.__MdSnackBar_85 == null)) { (this.__MdSnackBar_85 = new import6.MdSnackBar(this._Overlay_69,this._LiveAnnouncer_73,this.parent.get(import6.MdSnackBar,(null as any)))); }
    return this.__MdSnackBar_85;
  }
  get _D3Service_86():import9.D3Service {
    if ((this.__D3Service_86 == null)) { (this.__D3Service_86 = new import9.D3Service()); }
    return this.__D3Service_86;
  }
  get _DialogsService_87():import10.DialogsService {
    if ((this.__DialogsService_87 == null)) { (this.__DialogsService_87 = new import10.DialogsService()); }
    return this.__DialogsService_87;
  }
  createInternal():import1.CoreModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ɵba_1 = new import3.ɵba();
    this._FormsModule_2 = new import3.FormsModule();
    this._ɵa_3 = import4.ɵd(this.parent.get(import4.Router,(null as any)));
    this._UrlSerializer_4 = new import4.DefaultUrlSerializer();
    this._RouterOutletMap_5 = new import4.RouterOutletMap();
    this._ROUTER_CONFIGURATION_6 = {useHash: true};
    this._LocationStrategy_7 = import4.ɵc(this.parent.get(import2.PlatformLocation),this.parent.get(import2.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_6);
    this._Location_8 = new import2.Location(this._LocationStrategy_7);
    this._NgModuleFactoryLoader_9 = new import0.SystemJsNgModuleLoader(this.parent.get(import0.Compiler),this.parent.get(import0.SystemJsNgModuleLoaderConfig,(null as any)));
      this._ROUTES_10 = [[
        {
          path: '',
          redirectTo: 'instruction',
          pathMatch: 'full'
        }
        ,
        {
          path: 'instruction',
          component: import17.InstructionComponent
        }
        ,
        {
          path: 'modeling',
          component: import18.ModelingComponent
        }
        ,
        {
          path: '**',
          component: import19.Page404Component
        }

      ]
    ];
    this._Router_11 = import4.ɵe(this.parent.get(import0.ApplicationRef),this._UrlSerializer_4,this._RouterOutletMap_5,this._Location_8,this,this._NgModuleFactoryLoader_9,this.parent.get(import0.Compiler),this._ROUTES_10,this._ROUTER_CONFIGURATION_6,this.parent.get(import4.UrlHandlingStrategy,(null as any)),this.parent.get(import4.RouteReuseStrategy,(null as any)));
    this._RouterModule_12 = new import4.RouterModule(this._ɵa_3,this._Router_11);
    this._AppRoutingModule_13 = new import5.AppRoutingModule();
    this._PortalModule_14 = new import6.PortalModule();
    this._OverlayModule_15 = new import6.OverlayModule();
    this._PlatformModule_16 = new import6.PlatformModule();
    this._A11yModule_17 = new import6.A11yModule();
    this._CompatibilityModule_18 = new import6.CompatibilityModule(this.parent.get(import16.DOCUMENT,(null as any)));
    this._MdDialogModule_19 = new import6.MdDialogModule();
    this._MdRippleModule_20 = new import6.MdRippleModule();
    this._MdSelectionModule_21 = new import6.MdSelectionModule();
    this._MdOptionModule_22 = new import6.MdOptionModule();
    this._MdAutocompleteModule_23 = new import6.MdAutocompleteModule();
    this._StyleModule_24 = new import6.StyleModule();
    this._MdButtonModule_25 = new import6.MdButtonModule();
    this._MdButtonToggleModule_26 = new import6.MdButtonToggleModule();
    this._MdCardModule_27 = new import6.MdCardModule();
    this._MdChipsModule_28 = new import6.MdChipsModule();
    this._MdCheckboxModule_29 = new import6.MdCheckboxModule();
    this._MdLineModule_30 = new import6.MdLineModule();
    this._MdGridListModule_31 = new import6.MdGridListModule();
    this._HttpModule_32 = new import7.HttpModule();
    this._MdIconModule_33 = new import6.MdIconModule();
    this._MdInputModule_34 = new import6.MdInputModule();
    this._MdListModule_35 = new import6.MdListModule();
    this._MdMenuModule_36 = new import6.MdMenuModule();
    this._MdProgressBarModule_37 = new import6.MdProgressBarModule();
    this._MdProgressSpinnerModule_38 = new import6.MdProgressSpinnerModule();
    this._MdRadioModule_39 = new import6.MdRadioModule();
    this._MdSelectModule_40 = new import6.MdSelectModule();
    this._MdSidenavModule_41 = new import6.MdSidenavModule();
    this._RtlModule_42 = new import6.RtlModule();
    this._MdSliderModule_43 = new import6.MdSliderModule();
    this._MdSlideToggleModule_44 = new import6.MdSlideToggleModule();
    this._MdSnackBarModule_45 = new import6.MdSnackBarModule();
    this._ObserveContentModule_46 = new import6.ObserveContentModule();
    this._MdTabsModule_47 = new import6.MdTabsModule();
    this._MdToolbarModule_48 = new import6.MdToolbarModule();
    this._MdTooltipModule_49 = new import6.MdTooltipModule();
    this._MaterialModule_50 = new import6.MaterialModule();
    this._SharedModule_51 = new import8.SharedModule();
    this._CoreModule_52 = new import1.CoreModule();
    return this._CoreModule_52;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ɵba)) { return this._ɵba_1; }
    if ((token === import3.FormsModule)) { return this._FormsModule_2; }
    if ((token === import4.ɵa)) { return this._ɵa_3; }
    if ((token === import4.UrlSerializer)) { return this._UrlSerializer_4; }
    if ((token === import4.RouterOutletMap)) { return this._RouterOutletMap_5; }
    if ((token === import4.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_6; }
    if ((token === import2.LocationStrategy)) { return this._LocationStrategy_7; }
    if ((token === import2.Location)) { return this._Location_8; }
    if ((token === import0.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_9; }
    if ((token === import4.ROUTES)) { return this._ROUTES_10; }
    if ((token === import4.Router)) { return this._Router_11; }
    if ((token === import4.RouterModule)) { return this._RouterModule_12; }
    if ((token === import5.AppRoutingModule)) { return this._AppRoutingModule_13; }
    if ((token === import6.PortalModule)) { return this._PortalModule_14; }
    if ((token === import6.OverlayModule)) { return this._OverlayModule_15; }
    if ((token === import6.PlatformModule)) { return this._PlatformModule_16; }
    if ((token === import6.A11yModule)) { return this._A11yModule_17; }
    if ((token === import6.CompatibilityModule)) { return this._CompatibilityModule_18; }
    if ((token === import6.MdDialogModule)) { return this._MdDialogModule_19; }
    if ((token === import6.MdRippleModule)) { return this._MdRippleModule_20; }
    if ((token === import6.MdSelectionModule)) { return this._MdSelectionModule_21; }
    if ((token === import6.MdOptionModule)) { return this._MdOptionModule_22; }
    if ((token === import6.MdAutocompleteModule)) { return this._MdAutocompleteModule_23; }
    if ((token === import6.StyleModule)) { return this._StyleModule_24; }
    if ((token === import6.MdButtonModule)) { return this._MdButtonModule_25; }
    if ((token === import6.MdButtonToggleModule)) { return this._MdButtonToggleModule_26; }
    if ((token === import6.MdCardModule)) { return this._MdCardModule_27; }
    if ((token === import6.MdChipsModule)) { return this._MdChipsModule_28; }
    if ((token === import6.MdCheckboxModule)) { return this._MdCheckboxModule_29; }
    if ((token === import6.MdLineModule)) { return this._MdLineModule_30; }
    if ((token === import6.MdGridListModule)) { return this._MdGridListModule_31; }
    if ((token === import7.HttpModule)) { return this._HttpModule_32; }
    if ((token === import6.MdIconModule)) { return this._MdIconModule_33; }
    if ((token === import6.MdInputModule)) { return this._MdInputModule_34; }
    if ((token === import6.MdListModule)) { return this._MdListModule_35; }
    if ((token === import6.MdMenuModule)) { return this._MdMenuModule_36; }
    if ((token === import6.MdProgressBarModule)) { return this._MdProgressBarModule_37; }
    if ((token === import6.MdProgressSpinnerModule)) { return this._MdProgressSpinnerModule_38; }
    if ((token === import6.MdRadioModule)) { return this._MdRadioModule_39; }
    if ((token === import6.MdSelectModule)) { return this._MdSelectModule_40; }
    if ((token === import6.MdSidenavModule)) { return this._MdSidenavModule_41; }
    if ((token === import6.RtlModule)) { return this._RtlModule_42; }
    if ((token === import6.MdSliderModule)) { return this._MdSliderModule_43; }
    if ((token === import6.MdSlideToggleModule)) { return this._MdSlideToggleModule_44; }
    if ((token === import6.MdSnackBarModule)) { return this._MdSnackBarModule_45; }
    if ((token === import6.ObserveContentModule)) { return this._ObserveContentModule_46; }
    if ((token === import6.MdTabsModule)) { return this._MdTabsModule_47; }
    if ((token === import6.MdToolbarModule)) { return this._MdToolbarModule_48; }
    if ((token === import6.MdTooltipModule)) { return this._MdTooltipModule_49; }
    if ((token === import6.MaterialModule)) { return this._MaterialModule_50; }
    if ((token === import8.SharedModule)) { return this._SharedModule_51; }
    if ((token === import1.CoreModule)) { return this._CoreModule_52; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_53; }
    if ((token === import3.ɵi)) { return this._ɵi_54; }
    if ((token === import4.ActivatedRoute)) { return this._ActivatedRoute_55; }
    if ((token === import4.NoPreloading)) { return this._NoPreloading_56; }
    if ((token === import4.PreloadingStrategy)) { return this._PreloadingStrategy_57; }
    if ((token === import4.RouterPreloader)) { return this._RouterPreloader_58; }
    if ((token === import4.PreloadAllModules)) { return this._PreloadAllModules_59; }
    if ((token === import0.NgProbeToken)) { return this._NgProbeToken_60; }
    if ((token === import4.ɵg)) { return this._ɵg_61; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_62; }
    if ((token === import4.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_63; }
    if ((token === import0.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_64; }
    if ((token === import6.OverlayContainer)) { return this._OverlayContainer_65; }
    if ((token === import6.ScrollDispatcher)) { return this._ScrollDispatcher_66; }
    if ((token === import6.ɵh)) { return this._ɵh_67; }
    if ((token === import6.ɵk)) { return this._ɵk_68; }
    if ((token === import6.Overlay)) { return this._Overlay_69; }
    if ((token === import6.Platform)) { return this._Platform_70; }
    if ((token === import6.InteractivityChecker)) { return this._InteractivityChecker_71; }
    if ((token === import6.FocusTrapFactory)) { return this._FocusTrapFactory_72; }
    if ((token === import6.LiveAnnouncer)) { return this._LiveAnnouncer_73; }
    if ((token === import6.MdDialog)) { return this._MdDialog_74; }
    if ((token === import6.FocusOriginMonitor)) { return this._FocusOriginMonitor_75; }
    if ((token === import6.UniqueSelectionDispatcher)) { return this._UniqueSelectionDispatcher_76; }
    if ((token === import7.BrowserXhr)) { return this._BrowserXhr_77; }
    if ((token === import7.ResponseOptions)) { return this._ResponseOptions_78; }
    if ((token === import7.XSRFStrategy)) { return this._XSRFStrategy_79; }
    if ((token === import7.XHRBackend)) { return this._XHRBackend_80; }
    if ((token === import7.RequestOptions)) { return this._RequestOptions_81; }
    if ((token === import7.Http)) { return this._Http_82; }
    if ((token === import6.MdIconRegistry)) { return this._MdIconRegistry_83; }
    if ((token === import16.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_84; }
    if ((token === import6.MdSnackBar)) { return this._MdSnackBar_85; }
    if ((token === import9.D3Service)) { return this._D3Service_86; }
    if ((token === import10.DialogsService)) { return this._DialogsService_87; }
    return notFoundResult;
  }
  destroyInternal():void {
    (this.__RouterPreloader_58 && this._RouterPreloader_58.ngOnDestroy());
  }
}
export const CoreModuleNgFactory:import0.NgModuleFactory<import1.CoreModule> = new import0.NgModuleFactory<any>(CoreModuleInjector,import1.CoreModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvaW50ZXJuZXQvRG9jdW1lbnRzL0dpdEh1Yi9hbmd1bGFyMi9nZW5fZHJpZnQtbmdyeC00LXJjMy9hcHAvY29yZS9jb3JlLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9pbnRlcm5ldC9Eb2N1bWVudHMvR2l0SHViL2FuZ3VsYXIyL2dlbl9kcmlmdC1uZ3J4LTQtcmMzL2FwcC9jb3JlL2NvcmUubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
