/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


export const styles:any[] = ['h2[_ngcontent-%COMP%]{\r\n    text-align : center;\r\n}\r\n.modeling__inputs[_ngcontent-%COMP%]{\r\n    display : inline-block;\r\n}\r\nform[_ngcontent-%COMP%]{\r\n    text-align : center;\r\n    position : relative;\r\n    width : 990px;\r\n}\r\n#graphView[_ngcontent-%COMP%]{\r\n    display: -webkit-box;\r\n    display: -moz-box;\r\n    display: -ms-flexbox;\r\n    display: -webkit-flex;\r\n    display: flex;\r\n    -webkit-flex-flow: row wrap;\r\n    flex-flow: row wrap;\r\n    -webkit-justify-content: space-around;\r\n    justify-content: space-around;\r\n}\r\n@media (max-width: 1024px) {\r\n    #graphView[_ngcontent-%COMP%] {\r\n        width: 100%;\r\n    }\r\n    form[_ngcontent-%COMP%]{\r\n        width: 100%;\r\n    }\r\n}\r\n.wrapper__modeling[_ngcontent-%COMP%]{\r\n    border-top : 1px solid #AEAEAE;\r\n    -webkit-box-sizing : border-box;\r\n    -moz-box-sizing    : border-box;\r\n    box-sizing         : border-box;\r\n    background-color : #f5f5f5;\r\n    margin : 0 auto;\r\n    padding : 1px;\r\n    position : relative;\r\n    width : 980px;\r\n}\r\n@media (max-width: 980px) {\r\n    .wrapper[_ngcontent-%COMP%] {\r\n        width: 100%; }\r\n}\r\n.modeling__btn[_ngcontent-%COMP%]{\r\n    margin : 20px 50px;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvaW50ZXJuZXQvRG9jdW1lbnRzL0dpdEh1Yi9hbmd1bGFyMi9nZW5fZHJpZnQtbmdyeC00LXJjMy9hcHAvY29yZS9tb2RlbGluZy5jb21wb25lbnQvbW9kZWxpbmcuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9pbnRlcm5ldC9Eb2N1bWVudHMvR2l0SHViL2FuZ3VsYXIyL2dlbl9kcmlmdC1uZ3J4LTQtcmMzL2FwcC9jb3JlL21vZGVsaW5nLmNvbXBvbmVudC9tb2RlbGluZy5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
