/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../app/shared/modal_window.component/modal_window.component';
import * as import2 from '../../../node_modules/@angular/material/typings/index.ngfactory';
import * as import3 from '@angular/material';
import * as import4 from '../stub.component/stub.component.ngfactory';
import * as import5 from '../../../../app/shared/stub.component/stub.component';
const styles_ModalWindowComponent:any[] = ['h2[_ngcontent-%COMP%]{\n            text-align: center;\n            text-transform: uppercase;\n            margin: 0 0 0 40px;\n            padding: 0;\n        }\n        .modal-wndw__btn[_ngcontent-%COMP%]{\n            min-width: 40px;\n            padding: 0;\n            float: right;\n        }'];
export const RenderType_ModalWindowComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_ModalWindowComponent,
  data: {}
}
);
export function View_ModalWindowComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(2,[
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),4,'button',[
      [
        'class',
        'modal-wndw__btn'
      ]
      ,
      [
        'md-button',
        ''
      ]

    ]
    ,[
      [
        8,
        'disabled',
        0
      ]
      ,
      [
        2,
        'mat-button',
        (null as any)
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:import1.ModalWindowComponent = v.component;
      if (('click' === en)) {
        const pd_0:any = ((<any>co.dialogRef.close()) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },import2.View_MdButton_0,import2.RenderType_MdButton)),
      import0.ɵdid(8192,(null as any),0,import3.MdPrefixRejector,[[
        2,
        import3.MATERIAL_COMPATIBILITY_MODE
      ]
    ],(null as any),(null as any)),
    import0.ɵdid(90112,(null as any),0,import3.MdButton,[
      import0.ElementRef,
      import0.Renderer,
      import3.FocusOriginMonitor
    ]
    ,(null as any),(null as any)),
    import0.ɵdid(8192,(null as any),0,import3.MdButtonCssMatStyler,([] as any[]),(null as any),(null as any)),
    (l()(),import0.ɵted(0,['X'])),
    (l()(),import0.ɵted((null as any),['\n        '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),3,'h2',[[
        'md-dialog-title',
        ''
      ]
      ],[[
        2,
        'mat-dialog-title',
        (null as any)
      ]
    ],(null as any),(null as any),(null as any),(null as any))),
      import0.ɵdid(8192,(null as any),0,import3.MdPrefixRejector,[[
        2,
        import3.MATERIAL_COMPATIBILITY_MODE
      ]
    ],(null as any),(null as any)),
    import0.ɵdid(8192,(null as any),0,import3.MdDialogTitle,([] as any[]),(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),[
      '',
      ''
    ]
    )),
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'stub-cmpnt',([] as any[]),(null as any),(null as any),(null as any),import4.View_StubComponent_0,import4.RenderType_StubComponent)),
      import0.ɵdid(2121728,(null as any),0,import5.StubComponent,[import0.Renderer2],{body: [
        0,
        'body'
      ]
    },(null as any))
  ]
  ,(ck,v) => {
    var co:import1.ModalWindowComponent = v.component;
    const currVal_4:any = co.element;
    ck(v,13,0,currVal_4);
  },(ck,v) => {
    var co:import1.ModalWindowComponent = v.component;
    const currVal_0:any = import0.ɵnov(v,3).disabled;
    const currVal_1:any = true;
    ck(v,1,0,currVal_0,currVal_1);
    const currVal_2:any = true;
    ck(v,7,0,currVal_2);
    const currVal_3:any = co.title;
    ck(v,10,0,currVal_3);
  });
}
function View_ModalWindowComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'for-test',([] as any[]),(null as any),(null as any),(null as any),View_ModalWindowComponent_0,RenderType_ModalWindowComponent)),
    import0.ɵdid(24576,(null as any),0,import1.ModalWindowComponent,[import3.MdDialogRef],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const ModalWindowComponentNgFactory:import0.ComponentFactory<import1.ModalWindowComponent> = import0.ɵccf('for-test',import1.ModalWindowComponent,View_ModalWindowComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvaW50ZXJuZXQvRG9jdW1lbnRzL0dpdEh1Yi9hbmd1bGFyMi9nZW5fZHJpZnQtbmdyeC00LXJjMy9hcHAvc2hhcmVkL21vZGFsX3dpbmRvdy5jb21wb25lbnQvbW9kYWxfd2luZG93LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9pbnRlcm5ldC9Eb2N1bWVudHMvR2l0SHViL2FuZ3VsYXIyL2dlbl9kcmlmdC1uZ3J4LTQtcmMzL2FwcC9zaGFyZWQvbW9kYWxfd2luZG93LmNvbXBvbmVudC9tb2RhbF93aW5kb3cuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvaW50ZXJuZXQvRG9jdW1lbnRzL0dpdEh1Yi9hbmd1bGFyMi9nZW5fZHJpZnQtbmdyeC00LXJjMy9hcHAvc2hhcmVkL21vZGFsX3dpbmRvdy5jb21wb25lbnQvbW9kYWxfd2luZG93LmNvbXBvbmVudC50cy5Nb2RhbFdpbmRvd0NvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvaW50ZXJuZXQvRG9jdW1lbnRzL0dpdEh1Yi9hbmd1bGFyMi9nZW5fZHJpZnQtbmdyeC00LXJjMy9hcHAvc2hhcmVkL21vZGFsX3dpbmRvdy5jb21wb25lbnQvbW9kYWxfd2luZG93LmNvbXBvbmVudC50cy5Nb2RhbFdpbmRvd0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgICA8YnV0dG9uIG1kLWJ1dHRvbiBjbGFzcz1cIm1vZGFsLXduZHdfX2J0blwiXG4gICAgICAgICAgICAgICAgKGNsaWNrKT1cImRpYWxvZ1JlZi5jbG9zZSgpXCI+WDwvYnV0dG9uPlxuICAgICAgICA8aDIgbWQtZGlhbG9nLXRpdGxlPnt7IHRpdGxlIH19PC9oMj5cbiAgICAgICAgPHN0dWItY21wbnQgW3N0dWItY21wbnQtYm9keV09XCJlbGVtZW50XCI+PC9zdHViLWNtcG50PiIsIjxmb3ItdGVzdD48L2Zvci10ZXN0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7SUFDUTtNQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO0tBQUE7TUFBQTtRQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtRQUFBO01BQUE7O0lBQUE7T0FBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO01BQUE7TUFBQTtNQUNRO1FBQUE7UUFBQTtNQUFBO01BRFI7SUFBQTtrQkFBQTtRQUFBOztNQUFBO0lBQUE7Z0JBQUE7Ozs7SUFBQTtLQUFBO2dCQUFBO0lBQ29DO0lBQVU7TUFDOUM7UUFBQTtRQUFBO01BQUE7TUFBQTtRQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7a0JBQUE7UUFBQTs7TUFBQTtJQUFBO2dCQUFBO0lBQW9CO01BQUE7TUFBQTtJQUFBO0lBQUE7SUFBZ0I7SUFDcEM7a0JBQUE7UUFBQTtRQUFBO01BQUE7SUFBQTs7OztJQUFZO0lBQVosVUFBWSxTQUFaOzs7SUFIQTtJQUFBO0lBQUEsU0FBQSxVQUFBLFNBQUE7SUFFQTtJQUFBLFNBQUEsU0FBQTtJQUFvQjtJQUFBOzs7OztJQ0g1QjtnQkFBQTs7OzsifQ==
